version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: dream-shop-services
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: dream_shop_db
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: